server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petbbs?useSSL=false&autoReconnect=true
    username: root
    password: 123456
    dbcp2:
      validation-query: 'select 1'
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 27800
      initial-size: 5
      min-idle: 100
      max-wait-millis: 10000
