server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db
    username: root
    password: 123456
  h2:
    console:
      path: /h2-console
      enabled: true
